---
apiVersion: v1
offerings:
  - name: terraform-ibm-key-protect
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 17c52ab9-eb2e-4302-af2a-df41cac9eb2a
    examples:
      - name: basic
        mark_ready: true
